"""
Sphinx configuration for the adminata-doctrine-orm-admin-bundle documentation.

The documentation tree that came with `sonata-project/doctrine-orm-admin-bundle`, which lived in
the adminata repository's site while this package was a directory there. Upstream's file was
generated by `sonata-project/dev-kit` and carried a "DO NOT EDIT" banner; this one is written by
hand, because the fork's documentation is not generated by anything.

`nitpicky` is deliberate. The build is part of CI, and a warning is an error, so a cross-reference
that stops resolving when a page is pruned fails the build rather than shipping a dead link.
"""

from pygments.lexers.web import PhpLexer
from sphinx.highlighting import lexers

project = 'adminata-doctrine-orm-admin-bundle'
copyright = '2026, IDCT Bartosz Pachołek; 2010-2025 Thomas Rabaix and the Sonata contributors'
author = 'IDCT Bartosz Pachołek'

extensions = ['sphinx_rtd_theme']
templates_path = ['_templates']
# `_*.rst` are include fragments, not pages, so they are not part of any toctree.
exclude_patterns = ['_build', 'requirements.txt', '_*.rst', '**/_*.rst']

# PHP without an opening tag is the norm in these pages, and it is what upstream configured.
highlight_language = 'php'

for name in ('php', 'php-annotations', 'php-attributes', 'php-standalone', 'php-symfony'):
    lexers[name] = PhpLexer(startinline=True)

html_theme = 'sphinx_rtd_theme'
html_title = 'adminata Doctrine ORM Admin'

# No `html_static_path`: adminata ships no stylesheet or image of its own for the site, and an
# empty `_static/` is not a directory git can carry — which is exactly how this first reached CI
# as a warning the local build did not have.

htmlhelp_basename = 'adminata'

# Every `:doc:` and `:ref:` has to resolve.
nitpicky = True
